### ISSUE TITLE
 Does not work on Debian with numbers greater than 1 byte

### ISSUE THREAD

**Issue by PedroExpedito** [wallace0x7d0/big-integers#1]
Code Example: 

```c
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

//test
#include <time.h>
//test

#include "../bn.h"

int main(){

  BIGNUM *base      = int_to_bn(2);
  BIGNUM *expoente  = int_to_bn(8);
  BIGNUM *resultado = init_bn();

  pow_bn(base, expoente, resultado);
  println_bn(resultado);

  free_bn(base);
  free_bn(expoente);
  free_bn(resultado);

	return 0;
}
``` 
expected output: +256
output is: +6

Info: 

gcc (Debian 8.3.0-6) 8.3.0

Debian GNU/Linux 10 (buster)

Tips:

* Use Makefile
* Do not send binary to the repository

Obs:
Numbers larger than 32 bits also do not.

**Comment by opallace** [comment]
- Boa noite pedro, poderia me informar como esta compilando o código?
- A entrada da função int_to_bn() é um inteiro de 32bits, para inicializar um número maior que 32bits pode usar a função str_to_bn()
- Estou usando debian e executei o mesmo código que você e obtive +256 como o resultado esperado.

No aguardo de mais detalhes...

**Comment by PedroExpedito** [comment]
```gcc tests.c ../bn.c -o runme```

**Comment by opallace** [comment]
baixe o bn.o e compile gcc tests.c -o tests ../bn.o e execute ./tests

**Comment by PedroExpedito** [comment]
Não, Não vou usar uma LIB que não tenho o código fonte.

**Comment by opallace** [comment]
para gerar o bn.o a partir do bn.c basta fazer o seguinte gcc -c bn.c
